name: CI Build
on:
  push:
    branches:
      - '*'
      - '!master'

jobs:

  linux_build_parallel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Set up AdoptOpenJDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: x64
      - id: get-id
        run: |
          id=$(grep -oPm1 "(?<=<version>)[^<]+" "pom.xml")
          echo "id=$id" >> $GITHUB_OUTPUT
      #       - name: Setup tmate session
      #         uses: mxschmitt/action-tmate@v3
      - name: Publish package
        run: |
          mvn -B package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Java 14 Package API, create Linux binary
        run: |
          ls -la target
          rm -rf target/fireflyluciferin-${{steps.get-id.outputs.id}}.jar;
          mv target/FireflyLuciferin-${{steps.get-id.outputs.id}}-jar-with-dependencies.jar target/FireflyLuciferin-jar-with-dependencies.jar
          jpackage -i target --main-class org.dpsoftware.JavaFXStarter --main-jar FireflyLuciferin-jar-with-dependencies.jar --icon data/img/luciferin_logo.png --linux-shortcut --copyright "Davide Perini" --name FireflyLuciferin  --vendor DPsoftware --app-version "${{steps.get-id.outputs.id}}" --java-options "-XX:+UseZGC -XX:+ZGenerational -XX:+UseStringDeduplication -Xms64m -Xmx1024m"
      - name: Adding Linux asset to the release (Debian flavour)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mv firefly* FireflyLuciferinLinux.deb;
      - name: Creating artifact from BIN file
        uses: actions/upload-artifact@v3
        with:
          name: FireflyLuciferinLinux_${{steps.get-id.outputs.id}}_ALPHA.deb
          path: FireflyLuciferinLinux.deb
      - name: Adding Linux asset to the release (RedHat flavour)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo apt install alien -y;
          sudo alien -r FireflyLuciferinLinux.deb
          mv *.rpm FireflyLuciferinLinux.rpm;
      - name: Creating artifact from BIN file
        uses: actions/upload-artifact@v3
        with:
          name: FireflyLuciferinLinux_${{steps.get-id.outputs.id}}_ALPHA.rpm
          path: FireflyLuciferinLinux.rpm

